import os

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(ROOT_DIR, '..', 'data')

SEED = 789654
PROBLEM_INSTANCE_INDEX = 21

MAX_ITERATIONS = 50
THRESHOLD = 5

LOWER_BOUND = 8
UPPER_BOUND = 16

POPULATION_SIZE = 20
TOURNAMENT_SIZE = 4
MAX_GENERATIONS = 30
CROSSOVER_PROBABILITY = 0.7
MUTATION_PROBABILITY = 0.3

FITNESS_FUNCTION = 'MedAE'
