import os

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(ROOT_DIR, '..', 'data')

#
SEED = 5778856
PROBLEM_INSTANCE_INDEX = 7

NUMBER_OF_GENERATIONS = 200

MAX_ITERATIONS = 50
THRESHOLD = 5

LOWER_BOUND = 8
UPPER_BOUND = 16

POPULATION_SIZE = 200
TOURNAMENT_SIZE = 4
MAX_GENERATIONS = 200
CROSSOVER_PROBABILITY = 0.7
MUTATION_PROBABILITY = 0.3
