import os

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(ROOT_DIR, '..', 'data')

#
SEED = 8
PROBLEM_INSTANCE_INDEX = 21

NUMBER_OF_GENERATIONS = 100

MAX_ITERATIONS = 50
THRESHOLD = 5

LOWER_BOUND = 8
UPPER_BOUND = 16

POPULATION_SIZE = 100
TOURNAMENT_SIZE = 4
MAX_GENERATIONS = 100
CROSSOVER_PROBABILITY = 0.7
MUTATION_PROBABILITY = 0.3
